**Кейс-задача №3**

- Спроектируйте базу данных «Туризм» (перечень предоставляемых услуг, заказ туров и др.). При проектировании базы данных необходимо создать 4-5 таблиц предметной области: 3-4 таблицы-справочника и 1 таблицу переменной информации. Для всех таблиц создать первичные ключи. Построить связи между таблицами при помощи внешних ключей: атрибуты таблицы переменной информации должны ссылаться на ключевые атрибуты таблиц справочников.

- Когда вы создаете базу данных в MySQL с помощью MySQL Workbench (или любого другого инструмента), вы можете экспортировать схему базы данных в виде скрипта SQL. Этот скрипт SQL содержит определения таблиц, связей, индексов и других структур базы данных, которые вы создали. Или иным удобным для Вас способом.

****База данных создана на PostgreSQL в DBeaver 25.1.2****

In [ ]:
-- DROP SCHEMA "Tourism";

CREATE SCHEMA "Tourism" AUTHORIZATION postgres;

-- DROP SEQUENCE "Tourism".clients_client_id_seq;

CREATE SEQUENCE "Tourism".clients_client_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE "Tourism".countries_country_id_seq;

CREATE SEQUENCE "Tourism".countries_country_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE "Tourism".employees_employee_id_seq;

CREATE SEQUENCE "Tourism".employees_employee_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE "Tourism".orders_order_id_seq;

CREATE SEQUENCE "Tourism".orders_order_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE "Tourism".services_service_id_seq;

CREATE SEQUENCE "Tourism".services_service_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;-- "Tourism".clients определение

-- Drop table

-- DROP TABLE "Tourism".clients;

CREATE TABLE "Tourism".clients (
	client_id serial4 NOT NULL,
	first_name varchar(50) NOT NULL,
	last_name varchar(50) NOT NULL,
	phone varchar(20) NOT NULL,
	email varchar(100) NULL,
	passport_number varchar(20) NOT NULL,
	registration_date date DEFAULT CURRENT_DATE NOT NULL,
	CONSTRAINT clients_email_key UNIQUE (email),
	CONSTRAINT clients_passport_number_key UNIQUE (passport_number),
	CONSTRAINT clients_pkey PRIMARY KEY (client_id)
);


-- "Tourism".countries определение

-- Drop table

-- DROP TABLE "Tourism".countries;

CREATE TABLE "Tourism".countries (
	country_id serial4 NOT NULL,
	country_name varchar(100) NOT NULL,
	visa_required bool DEFAULT false NOT NULL,
	climate varchar(50) NULL,
	popular_season varchar(50) NULL,
	CONSTRAINT countries_country_name_key UNIQUE (country_name),
	CONSTRAINT countries_pkey PRIMARY KEY (country_id)
);


-- "Tourism".employees определение

-- Drop table

-- DROP TABLE "Tourism".employees;

CREATE TABLE "Tourism".employees (
	employee_id serial4 NOT NULL,
	first_name varchar(50) NOT NULL,
	last_name varchar(50) NOT NULL,
	"position" varchar(100) NOT NULL,
	hire_date date NOT NULL,
	phone varchar(20) NOT NULL,
	email varchar(100) NULL,
	CONSTRAINT employees_email_key UNIQUE (email),
	CONSTRAINT employees_pkey PRIMARY KEY (employee_id)
);


-- "Tourism".services определение

-- Drop table

-- DROP TABLE "Tourism".services;

CREATE TABLE "Tourism".services (
	service_id serial4 NOT NULL,
	service_name varchar(100) NOT NULL,
	description text NULL,
	price numeric(10, 2) NOT NULL,
	duration_days int4 NOT NULL,
	is_active bool DEFAULT true NOT NULL,
	CONSTRAINT services_pkey PRIMARY KEY (service_id),
	CONSTRAINT services_service_name_key UNIQUE (service_name)
);


-- "Tourism".orders определение

-- Drop table

-- DROP TABLE "Tourism".orders;

CREATE TABLE "Tourism".orders (
	order_id serial4 NOT NULL,
	client_id int4 NOT NULL,
	service_id int4 NOT NULL,
	country_id int4 NOT NULL,
	employee_id int4 NOT NULL,
	order_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	departure_date date NOT NULL,
	return_date date NOT NULL,
	total_price numeric(10, 2) NOT NULL,
	payment_status varchar(20) DEFAULT 'pending'::character varying NOT NULL,
	notes text NULL,
	CONSTRAINT orders_check CHECK ((departure_date > order_date)),
	CONSTRAINT orders_check1 CHECK ((return_date > departure_date)),
	CONSTRAINT orders_payment_status_check CHECK (((payment_status)::text = ANY ((ARRAY['pending'::character varying, 'paid'::character varying, 'canceled'::character varying])::text[]))),
	CONSTRAINT orders_pkey PRIMARY KEY (order_id),
	CONSTRAINT orders_client_id_fkey FOREIGN KEY (client_id) REFERENCES "Tourism".clients(client_id),
	CONSTRAINT orders_country_id_fkey FOREIGN KEY (country_id) REFERENCES "Tourism".countries(country_id),
	CONSTRAINT orders_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES "Tourism".employees(employee_id),
	CONSTRAINT orders_service_id_fkey FOREIGN KEY (service_id) REFERENCES "Tourism".services(service_id)
);